[package]
name = "mxc-alpha-wslc-common"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Windows Subsystem for Linux container backend support for MXC."

[features]
default = []
link-wslcsdk = []

[dependencies]
mxc-alpha-wxc-common = { workspace = true }
tar = "0.4"
libloading = "0.8"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true }

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
zip = { version = "2", default-features = false, features = ["deflate"] }
sha2 = "0.10"
