[package]
name = "wslc_common"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
link-wslcsdk = []

[dependencies]
wxc_common = { workspace = true }
windows = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
tar = "0.4"
libloading = "0.8"

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
zip = { version = "2", default-features = false, features = ["deflate"] }
sha2 = "0.10"
