[package]
name = "mxc-bwrap-common"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Bubblewrap Linux backend support for MXC sandboxing."

[lib]
name = "bwrap_common"

[dependencies]
wxc_common = { workspace = true }
lxc_common = { workspace = true }
nix = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
