[package]
name = "lxc"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "lxc-exec"
path = "src/main.rs"

[features]
hyperlight = ["dep:hyperlight_common", "hyperlight_common/hyperlight", "mxc_engine/hyperlight"]
microvm = ["mxc_engine/microvm"]

[build-dependencies]
mxc_build_common.workspace = true

[dependencies]
wxc_common = { workspace = true }
mxc_engine = { workspace = true }
lxc_common = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
[target.'cfg(target_arch = "x86_64")'.dependencies]
hyperlight_common = { workspace = true, optional = true }
