id: labelManagement.issueAssigned
name: GitOps.PullRequestIssueManagement
description: Handlers when an issue is assigned to a user
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Remove Needs-Triage label when an issue is assigned
        if:
          - payloadType: Issues
          - isAction:
              action: Assigned
        then:
          - removeLabel:
              label: Needs-Triage
onFailure:
onSuccess:
