[package]
name = "mxc_alpha_nanvix_runner"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "NanVix micro-VM runner used by the MXC execution engine."

[dependencies]
mxc_alpha_wxc_common = { workspace = true, features = ["microvm"] }
mxc_alpha_nanvix_common = { path = "../common", version = "0.7.0" }
uuid = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
libc = { workspace = true }
