// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// @generated by scripts/versioning/generate-schema-version-metadata.js.
// Do not edit by hand.

use crate::models::ContainmentBackend;
use mxc_config_contract::ContractVersion;

pub fn state_aware_contract(backend: &ContainmentBackend) -> Option<ContractVersion> {
    match backend {
        ContainmentBackend::IsolationSession => Some(ContractVersion::V0_9_0Alpha),
        ContainmentBackend::WindowsSandbox => Some(ContractVersion::V0_10_0Alpha),
        ContainmentBackend::Wslc => Some(ContractVersion::V0_9_0Alpha),
        ContainmentBackend::ProcessContainer
        | ContainmentBackend::Lxc
        | ContainmentBackend::Vm
        | ContainmentBackend::MicroVm
        | ContainmentBackend::Hyperlight
        | ContainmentBackend::Seatbelt
        | ContainmentBackend::Bubblewrap => None,
    }
}
