// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Pure Rust TraceLogging ETW telemetry for MXC.
//!
//! This crate provides the `Microsoft.MXC` ETW TraceLogging provider using the
//! [`tracelogging`](https://crates.io/crates/tracelogging) crate — no C++ shim
//! or WIL dependency required.
//!
//! # Platform behaviour
//!
//! - **Windows**: Events are emitted via the ETW `EventWriteTransfer` API.
//!   Each event includes a `COMMON_MXC_PARAMS` struct containing Version,
//!   Channel, IsDebugging, and `UTCReplace_AppSessionGuid`.
//! - **Non-Windows**: All functions are no-ops — the `tracelogging` crate
//!   compiles but produces no-op implementations on non-Windows targets.
//!
//! # Thread safety
//!
//! Provider state (version/channel strings) is stored in a `OnceLock` and is
//! immutable after first initialisation. The `tracelogging` provider is
//! internally synchronised.

// ---------------------------------------------------------------------------
// Windows provider implementation
// ---------------------------------------------------------------------------

#[cfg(target_os = "windows")]
mod provider {
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::OnceLock;

    // Provider definition generated by build.rs — includes `id(...)` and
    // optionally `group_id(...)` for internal Microsoft builds.
    include!(concat!(env!("OUT_DIR"), "/provider_def.rs"));

    /// Sampling keyword for Measures-level telemetry.
    /// Same value as WIL's `traceloggingconfig.h` `MICROSOFT_KEYWORD_MEASURES`.
    pub(crate) const MICROSOFT_KEYWORD_MEASURES: u64 = 0x0000_4000_0000_0000;

    /// Cached provider state, set once at init and read on every event.
    struct ProviderState {
        version: String,
        channel: String,
    }

    static STATE: OnceLock<ProviderState> = OnceLock::new();
    static REGISTERED: AtomicBool = AtomicBool::new(false);

    /// Register the ETW provider and cache version/channel strings.
    ///
    /// Returns `true` if the provider was successfully registered.
    /// A `true` return means the provider is registered — it does *not*
    /// guarantee an ETW session is actively listening.
    ///
    /// **Note:** Version and channel are captured on the **first** call only.
    /// Subsequent calls (even after [`shutdown`]) reuse the original values
    /// because the backing `OnceLock` cannot be reset.
    pub fn init(version: &str, channel: &str) -> bool {
        STATE.get_or_init(|| ProviderState {
            version: version.to_owned(),
            channel: channel.to_owned(),
        });

        // Only register once — the tracelogging crate panics on double register.
        if !REGISTERED.swap(true, Ordering::SeqCst) {
            // SAFETY: MXC_PROVIDER is a process-lifetime static. MXC is an
            // executable (not a DLL), so unload ordering is not a concern.
            unsafe {
                MXC_PROVIDER.register();
            }
        }

        true
    }

    /// Unregister the ETW provider.
    pub fn shutdown() {
        if REGISTERED.swap(false, Ordering::SeqCst) {
            MXC_PROVIDER.unregister();
        }
    }

    /// Emit an `MXC.Execution` ETW event.
    pub fn log_execution(
        backend: &str,
        exit_code: i32,
        outcome: &str,
        duration_ms: u64,
        failure_reason: &str,
    ) {
        let state = match STATE.get() {
            Some(s) => s,
            None => return,
        };

        // Compile-time flag — true for debug builds, false for release.
        // This is NOT a runtime IsDebuggerPresent() check; it mirrors
        // the MXC_CHANNEL logic for cross-platform consistency.
        let is_debug_build = cfg!(debug_assertions);

        tracelogging::write_event!(
            MXC_PROVIDER,
            "MXC.Execution",
            level(Informational),
            keyword(MICROSOFT_KEYWORD_MEASURES),
            struct("COMMON_MXC_PARAMS", {
                str8("Version", &state.version),
                str8("Channel", &state.channel),
                bool8("IsDebugging", &is_debug_build),
                bool8("UTCReplace_AppSessionGuid", &true),
            }),
            str8("mxc.backend", backend),
            i32("mxc.exit_code", &exit_code),
            str8("mxc.outcome", outcome),
            u64("mxc.duration_ms", &duration_ms),
            str8("mxc.failure_reason", failure_reason),
        );
    }

    /// Emit an `MXC.Error` ETW event.
    pub fn log_error(backend: &str, error_type: &str, error_message: &str) {
        let state = match STATE.get() {
            Some(s) => s,
            None => return,
        };

        let is_debug_build = cfg!(debug_assertions);

        tracelogging::write_event!(
            MXC_PROVIDER,
            "MXC.Error",
            level(Warning),
            keyword(MICROSOFT_KEYWORD_MEASURES),
            struct("COMMON_MXC_PARAMS", {
                str8("Version", &state.version),
                str8("Channel", &state.channel),
                bool8("IsDebugging", &is_debug_build),
                bool8("UTCReplace_AppSessionGuid", &true),
            }),
            str8("mxc.backend", backend),
            str8("mxc.error_type", error_type),
            str8("mxc.error_message", error_message),
        );
    }
}

// ---------------------------------------------------------------------------
// Non-Windows no-op stubs
// ---------------------------------------------------------------------------

#[cfg(not(target_os = "windows"))]
mod provider {
    pub fn init(_version: &str, _channel: &str) -> bool {
        false
    }

    pub fn shutdown() {}

    pub fn log_execution(
        _backend: &str,
        _exit_code: i32,
        _outcome: &str,
        _duration_ms: u64,
        _failure_reason: &str,
    ) {
    }

    pub fn log_error(_backend: &str, _error_type: &str, _error_message: &str) {}
}

pub use provider::*;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    /// The provider uses global state (`OnceLock`), so tests that call
    /// `init`/`shutdown` must not run concurrently.
    static TEST_LOCK: Mutex<()> = Mutex::new(());

    #[test]
    fn init_shutdown_roundtrip() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let ok = init("0.0.0-test", "dev");
        if cfg!(target_os = "windows") {
            assert!(ok, "init should succeed on Windows");
        } else {
            assert!(!ok, "init should be a no-op on non-Windows");
        }
        shutdown();
    }

    #[test]
    fn double_init_is_safe() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let _ = init("0.0.0-test", "dev");
        let _ = init("0.0.0-test", "dev");
        shutdown();
    }

    #[test]
    fn shutdown_without_init() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        shutdown();
    }

    #[test]
    fn log_execution_after_init() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let _ = init("0.0.0-test", "dev");
        log_execution("test_backend", 0, "success", 100, "");
        shutdown();
    }

    #[test]
    fn log_error_after_init() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let _ = init("0.0.0-test", "dev");
        log_error("test_backend", "config_error", "test error message");
        shutdown();
    }

    #[test]
    fn log_without_init() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        log_execution("test_backend", 0, "success", 50, "none");
        log_error("test_backend", "unknown", "no init");
    }

    #[test]
    fn log_after_shutdown() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let _ = init("0.0.0-test", "dev");
        shutdown();
        log_execution("test_backend", 1, "failure", 200, "timeout");
        log_error("test_backend", "process_error", "after shutdown");
    }

    #[test]
    fn handles_empty_strings() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let _ = init("", "");
        log_execution("", 0, "", 0, "");
        log_error("", "", "");
        shutdown();
    }
}
