// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Pure Rust TraceLogging ETW telemetry for MXC.
//!
//! This crate provides the `Microsoft.MXC` ETW TraceLogging provider using the
//! [`tracelogging`](https://crates.io/crates/tracelogging) crate — no C++ shim
//! or WIL dependency required.
//!
//! # Platform behaviour
//!
//! - **Windows**: Events are emitted via the ETW `EventWriteTransfer` API.
//!   Each event includes a `COMMON_MXC_PARAMS` struct containing Version,
//!   Channel, IsDebugging, and `UTCReplace_AppSessionGuid`.
//! - **Non-Windows**: All functions are no-ops — the `tracelogging` crate
//!   compiles but produces no-op implementations on non-Windows targets.
//!
//! # Thread safety
//!
//! Provider state (version/channel strings) is stored in a `OnceLock` and is
//! immutable after first initialisation. The `tracelogging` provider is
//! internally synchronised.

// ---------------------------------------------------------------------------
// Windows provider implementation
// ---------------------------------------------------------------------------

#[cfg(target_os = "windows")]
mod provider {
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::Mutex;
    use std::sync::OnceLock;

    // Provider definition generated by build.rs — includes `id(...)` and
    // optionally `group_id(...)` for internal Microsoft builds.
    include!(concat!(env!("OUT_DIR"), "/provider_def.rs"));

    /// Sampling keyword for Measures-level telemetry.
    /// Same value as WIL's `traceloggingconfig.h` `MICROSOFT_KEYWORD_MEASURES`.
    pub(crate) const MICROSOFT_KEYWORD_MEASURES: u64 = 0x0000_4000_0000_0000;

    /// Privacy data tag for Product and Service Usage.
    /// Same value as WIL's `MicrosoftTelemetry.h` `PDT_ProductAndServiceUsage`.
    /// Applied via a `PartA_PrivTags` field per the `TelemetryPrivacyDataTag` pattern.
    pub(crate) const PDT_PRODUCT_AND_SERVICE_USAGE: u64 = 0x0000_0000_0200_0000;

    /// Cached provider state, set once at init and read on every event.
    struct ProviderState {
        version: String,
        channel: String,
    }

    static STATE: OnceLock<ProviderState> = OnceLock::new();

    /// Tracks whether the ETW provider is currently registered.
    ///
    /// A `Mutex` (rather than an `AtomicBool`) is used so the wrapper's view of
    /// registration is updated **under the same lock that serialises the
    /// underlying `register`/`unregister` ETW calls**. This prevents a
    /// concurrent `init`/`shutdown` race from leaving the wrapper flag and the
    /// provider's real state out of sync (e.g. flag set to registered after a
    /// `register()` that actually failed, or a double register/unregister).
    static REGISTERED: Mutex<bool> = Mutex::new(false);

    /// Lock-free "is the provider currently registered" flag.
    ///
    /// Mirrors [`REGISTERED`] but is readable without acquiring the mutex, so
    /// out-of-band emit paths that run in delicate contexts — the global panic
    /// hook (unwinding) and the console control handler (about to be torn down
    /// by the OS) — can cheaply skip work when telemetry is inactive without
    /// risking a mutex acquisition. It is written **inside** the `REGISTERED`
    /// critical section so the two never disagree about the final state.
    static ACTIVE: AtomicBool = AtomicBool::new(false);

    /// Returns `true` if the ETW provider is currently registered.
    ///
    /// Cheap and lock-free — intended for guarding best-effort emit paths such
    /// as [`emit_panic`](crate)-style hooks. May momentarily lag a concurrent
    /// `init`/`shutdown`, which is acceptable for best-effort telemetry.
    pub fn is_active() -> bool {
        ACTIVE.load(Ordering::Acquire)
    }

    /// Register the ETW provider and cache version/channel strings.
    ///
    /// Returns `true` if the provider is registered on return. A `true` return
    /// means the provider is registered — it does *not* guarantee an ETW
    /// session is actively listening. Returns `false` if the underlying
    /// `register()` call reported a non-zero Win32 status, in which case the
    /// provider is left unregistered so a later call may retry and callers
    /// treat telemetry as inactive.
    ///
    /// **Note:** Version and channel are captured on the **first** call only.
    /// Subsequent calls (even after [`shutdown`]) reuse the original values
    /// because the backing `OnceLock` cannot be reset.
    pub fn init(version: &str, channel: &str) -> bool {
        STATE.get_or_init(|| ProviderState {
            version: version.to_owned(),
            channel: channel.to_owned(),
        });

        let mut registered = REGISTERED.lock().unwrap_or_else(|e| e.into_inner());
        if *registered {
            // Already registered — the tracelogging crate panics on double
            // register, so we must not call `register()` again.
            return true;
        }

        // SAFETY: MXC_PROVIDER is a process-lifetime static. MXC is an
        // executable (not a DLL), so unload ordering is not a concern.
        let status = unsafe { MXC_PROVIDER.register() };
        if status != 0 {
            // Registration failed; leave `*registered` false so the wrapper
            // state matches reality and a later attempt can retry.
            return false;
        }

        *registered = true;
        ACTIVE.store(true, Ordering::Release);
        true
    }

    /// Unregister the ETW provider.
    pub fn shutdown() {
        let mut registered = REGISTERED.lock().unwrap_or_else(|e| e.into_inner());
        if *registered {
            MXC_PROVIDER.unregister();
            *registered = false;
            ACTIVE.store(false, Ordering::Release);
        }
    }

    /// Emit an `MXC.Execution` ETW event.
    ///
    /// `phase` is the state-aware lifecycle phase that produced this event —
    /// one of `provision|start|exec|stop|deprovision`. It is empty for one-shot
    /// (non-state-aware) executions, which have no lifecycle phase.
    ///
    /// `correlation_vector` is the Microsoft Correlation Vector (MS-CV) for this
    /// event, emitted under the reserved TraceLogging field name `__TlgCV__` (the
    /// same field WIL TraceLogging uses). It is seeded from random bytes at
    /// `provision` and spun per phase, so `provision`→…→`deprovision` events can
    /// be joined across the separate `wxc-exec` processes that emit them (join on
    /// the shared base prefix). Carries no `sandbox_id` / UPN or other caller
    /// identity — privacy-safe by construction. Empty for one-shot executions
    /// (which are a single process already correlated by `AppSessionGuid`).
    pub fn log_execution(
        backend: &str,
        exit_code: i32,
        outcome: &str,
        duration_ms: u64,
        failure_reason: &str,
        phase: &str,
        correlation_vector: &str,
    ) {
        let state = match STATE.get() {
            Some(s) => s,
            None => return,
        };

        // Compile-time flag — true for debug builds, false for release.
        // This is NOT a runtime IsDebuggerPresent() check; it mirrors
        // the MXC_CHANNEL logic for cross-platform consistency.
        let is_debug_build = cfg!(debug_assertions);

        tracelogging::write_event!(
            MXC_PROVIDER,
            "MXC.Execution",
            // Informational: every completion (success or failure) is a routine
            // "what happened" record, not a fault. Severity is reserved for
            // MXC.Error (Warning) and any future provider malfunction.
            level(Informational),
            keyword(MICROSOFT_KEYWORD_MEASURES),
            u64("PartA_PrivTags", &PDT_PRODUCT_AND_SERVICE_USAGE),
            struct("COMMON_MXC_PARAMS", {
                str8("Version", &state.version),
                str8("Channel", &state.channel),
                bool8("IsDebugging", &is_debug_build),
                bool8("UTCReplace_AppSessionGuid", &true),
            }),
            str8("mxc.backend", backend),
            i32("mxc.exit_code", &exit_code),
            str8("mxc.outcome", outcome),
            u64("mxc.duration_ms", &duration_ms),
            str8("mxc.failure_reason", failure_reason),
            // State-aware lifecycle phase (provision|start|exec|stop|
            // deprovision); empty for one-shot executions.
            str8("mxc.phase", phase),
            // Microsoft Correlation Vector (MS-CV), under WIL TraceLogging's
            // reserved `__TlgCV__` field. Seeded at provision and spun per phase;
            // share a base prefix across all phases of one state-aware lifecycle.
            // Empty for one-shot executions. Join on the base prefix to
            // reconstruct a full provision→…→deprovision timeline.
            str8("__TlgCV__", correlation_vector),
        );
    }

    /// Emit an `MXC.Error` ETW event.
    ///
    /// By design this event carries **no free-form error text** — only the
    /// bounded `error_type` category and the process `exit_code`. This keeps
    /// telemetry free of PII (paths, usernames, credentials) that error
    /// strings can contain.
    ///
    /// `phase` is the state-aware lifecycle phase that produced this event
    /// (`provision|start|exec|stop|deprovision`); empty for one-shot executions.
    ///
    /// `correlation_vector` is the Microsoft Correlation Vector (MS-CV), emitted
    /// under `__TlgCV__` (see [`log_execution`]); empty for one-shot executions.
    pub fn log_error(
        backend: &str,
        error_type: &str,
        exit_code: i32,
        phase: &str,
        correlation_vector: &str,
    ) {
        let state = match STATE.get() {
            Some(s) => s,
            None => return,
        };

        let is_debug_build = cfg!(debug_assertions);

        tracelogging::write_event!(
            MXC_PROVIDER,
            "MXC.Error",
            // Warning, not Error/Critical: this reports an expected operational
            // failure of a *sandboxed run* (e.g. the user's script failed, a
            // backend was unavailable, a missing/rejected config) — not a
            // defect in MXC itself. Downstream pipelines treat Error/Critical as
            // product faults that feed reliability alerting, so those levels are
            // reserved for genuine provider/telemetry malfunctions.
            level(Warning),
            keyword(MICROSOFT_KEYWORD_MEASURES),
            u64("PartA_PrivTags", &PDT_PRODUCT_AND_SERVICE_USAGE),
            struct("COMMON_MXC_PARAMS", {
                str8("Version", &state.version),
                str8("Channel", &state.channel),
                bool8("IsDebugging", &is_debug_build),
                bool8("UTCReplace_AppSessionGuid", &true),
            }),
            str8("mxc.backend", backend),
            str8("mxc.error_type", error_type),
            i32("mxc.exit_code", &exit_code),
            // State-aware lifecycle phase (provision|start|exec|stop|
            // deprovision); empty for one-shot executions.
            str8("mxc.phase", phase),
            // MS-CV under `__TlgCV__` (see MXC.Execution); empty for one-shot.
            str8("__TlgCV__", correlation_vector),
        );
    }
}

// ---------------------------------------------------------------------------
// Non-Windows no-op stubs
// ---------------------------------------------------------------------------

#[cfg(not(target_os = "windows"))]
mod provider {
    pub fn init(_version: &str, _channel: &str) -> bool {
        false
    }

    pub fn shutdown() {}

    pub fn is_active() -> bool {
        false
    }

    pub fn log_execution(
        _backend: &str,
        _exit_code: i32,
        _outcome: &str,
        _duration_ms: u64,
        _failure_reason: &str,
        _phase: &str,
        _correlation_vector: &str,
    ) {
    }

    pub fn log_error(
        _backend: &str,
        _error_type: &str,
        _exit_code: i32,
        _phase: &str,
        _correlation_vector: &str,
    ) {
    }
}

pub use provider::*;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    /// The provider uses global state (`OnceLock`), so tests that call
    /// `init`/`shutdown` must not run concurrently.
    static TEST_LOCK: Mutex<()> = Mutex::new(());

    #[test]
    fn init_shutdown_roundtrip() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let ok = init("0.0.0-test", "dev");
        if cfg!(target_os = "windows") {
            assert!(ok, "init should succeed on Windows");
        } else {
            assert!(!ok, "init should be a no-op on non-Windows");
        }
        shutdown();
    }

    #[test]
    fn double_init_is_safe() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let _ = init("0.0.0-test", "dev");
        let _ = init("0.0.0-test", "dev");
        shutdown();
    }

    #[test]
    fn shutdown_without_init() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        shutdown();
    }

    #[test]
    fn is_active_tracks_registration() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let ok = init("0.0.0-test", "dev");
        // `is_active` reflects whether registration actually succeeded, which
        // matches `init`'s return on every platform (always false off Windows).
        assert_eq!(is_active(), ok);
        shutdown();
        assert!(!is_active(), "provider must be inactive after shutdown");
    }

    #[test]
    fn log_execution_after_init() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let _ = init("0.0.0-test", "dev");
        log_execution(
            "test_backend",
            0,
            "success",
            100,
            "",
            "provision",
            "iso:wxc-abcd",
        );
        shutdown();
    }

    #[test]
    fn log_error_after_init() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let _ = init("0.0.0-test", "dev");
        log_error(
            "test_backend",
            "config_error",
            1,
            "provision",
            "iso:wxc-abcd",
        );
        shutdown();
    }

    #[test]
    fn log_without_init() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        log_execution("test_backend", 0, "success", 50, "none", "", "");
        log_error("test_backend", "unknown", 1, "", "");
    }

    #[test]
    fn log_after_shutdown() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let _ = init("0.0.0-test", "dev");
        shutdown();
        log_execution(
            "test_backend",
            1,
            "failure",
            200,
            "timeout",
            "exec",
            "iso:wxc-abcd",
        );
        log_error("test_backend", "process_error", 1, "exec", "iso:wxc-abcd");
    }

    #[test]
    fn handles_empty_strings() {
        let _lock = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let _ = init("", "");
        log_execution("", 0, "", 0, "", "", "");
        log_error("", "", 0, "", "");
        shutdown();
    }
}

// ---------------------------------------------------------------------------
// Provider code-generation tests
// ---------------------------------------------------------------------------
//
// The build script's GUID validation and `define_provider!` code generation
// live in `provider_codegen.rs`. Cargo never runs `#[cfg(test)]` modules inside
// a build script, so we `include!` the same source here to exercise it under
// `cargo test`.
#[cfg(test)]
mod provider_codegen_tests {
    include!("../provider_codegen.rs");

    #[test]
    fn absent_guid_yields_plain_provider() {
        let def = generate_provider_def(None);
        assert!(def.contains("\"Microsoft.MXC\""));
        assert!(!def.contains("group_id"));
    }

    #[test]
    fn empty_guid_yields_plain_provider() {
        let def = generate_provider_def(Some(""));
        assert!(!def.contains("group_id"));
    }

    #[test]
    fn valid_guid_adds_group_id() {
        let def = generate_provider_def(Some("7f10def4-a258-5fea-510e-2c3bb976687f"));
        assert!(def.contains("group_id(\"7f10def4-a258-5fea-510e-2c3bb976687f\")"));
    }

    #[test]
    #[should_panic(expected = "not a valid GUID")]
    fn invalid_guid_panics() {
        let _ = generate_provider_def(Some("not-a-valid-guid"));
    }

    #[test]
    fn guid_validation_accepts_and_rejects() {
        assert!(is_valid_guid("7f10def4-a258-5fea-510e-2c3bb976687f"));
        // Missing dashes.
        assert!(!is_valid_guid("7f10def4a2585fea510e2c3bb976687f"));
        // Non-hex characters.
        assert!(!is_valid_guid("zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz"));
        // Wrong segment lengths.
        assert!(!is_valid_guid("7f10def-a258-5fea-510e-2c3bb976687f"));
    }
}
