// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Microsoft.Mxc.Sdk.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "mxc_ffi";





        /// <summary>
        ///  Run a sandbox to completion and capture its output.
        ///
        ///  Parses `policy_json_utf8` as a `SandboxPolicy`, sets `command_utf8` as the
        ///  command to run (the `process.commandLine` equivalent), runs the sandbox to
        ///  completion, and writes the outcome into `*out`.
        ///
        ///  Returns the resulting status code (also stored in `out-&gt;status`). Returns
        ///  [`MXC_STATUS_NULL_ARGUMENT`] without touching `*out` if `out` is null.
        ///
        ///  # Safety
        ///  - `policy_json_utf8` and `command_utf8` must be null or valid NUL-terminated
        ///    UTF-8 C strings.
        ///  - `out` must be null or point to writable [`MxcRunResult`]-sized storage.
        ///  - On success the caller must release `*out` with [`mxc_run_result_free`].
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mxc_run", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mxc_run(byte* policy_json_utf8, byte* command_utf8, MxcRunResult* @out);

        /// <summary>
        ///  Free the owned out-strings of an [`MxcRunResult`] produced by [`mxc_run`].
        ///
        ///  Safe to call once per result. The result struct itself is caller-owned
        ///  (typically stack storage); this frees only the heap strings it points to and
        ///  nulls them.
        ///
        ///  # Safety
        ///  `r` must be null or point to an [`MxcRunResult`] previously filled by
        ///  [`mxc_run`], not already freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mxc_run_result_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void mxc_run_result_free(MxcRunResult* r);

        /// <summary>
        ///  Free a single heap C string returned by this library.
        ///
        ///  # Safety
        ///  `s` must be null or a string previously returned by this library and not
        ///  already freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mxc_string_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void mxc_string_free(byte* s);

        /// <summary>
        ///  Return the library version as a static, NUL-terminated C string.
        ///
        ///  The pointer is valid for the lifetime of the process and must **not** be
        ///  freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mxc_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mxc_version();


    }

    /// <summary>
    ///  The result of an [`mxc_run`] call.
    ///
    ///  On success (`status == 0`), `exit_code` / `timed_out` describe how the
    ///  process finished and `stdout_utf8` / `stderr_utf8` carry its captured output
    ///  (`error_utf8` is null). On failure, `error_utf8` carries a human-readable
    ///  message and the output fields are null.
    ///
    ///  All non-null `*_utf8` pointers are owned by the caller and must be released
    ///  with [`mxc_run_result_free`].
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct MxcRunResult
    {
        /// <summary>
        ///  `0` on success; otherwise one of the `MXC_STATUS_*` codes.
        /// </summary>
        public int status;
        /// <summary>
        ///  The process exit code (valid when `status == 0` and `timed_out == 0`).
        /// </summary>
        public int exit_code;
        /// <summary>
        ///  `1` if the run hit its `scriptTimeout` and was killed, else `0`.
        /// </summary>
        public int timed_out;
        /// <summary>
        ///  Captured stdout (UTF-8, NUL-terminated), or null.
        /// </summary>
        public byte* stdout_utf8;
        /// <summary>
        ///  Captured stderr (UTF-8, NUL-terminated), or null.
        /// </summary>
        public byte* stderr_utf8;
        /// <summary>
        ///  Error message (UTF-8, NUL-terminated) when `status != 0`, else null.
        /// </summary>
        public byte* error_utf8;
    }



}
