// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

const test = require("node:test");
const assert = require("node:assert/strict");
const {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} = require("fs");
const { tmpdir } = require("os");
const { dirname, join } = require("path");
const { run: runGenerator } = require("../generate-schema-version-metadata.js");
const OUTPUTS = [
  join("src", "core", "wxc_common", "src", "schema_versions.rs"),
  join("sdk", "node", "src", "generated", "schema-versions.ts"),
  join(
    "sdk",
    "dotnet",
    "Microsoft.Mxc.Sdk",
    "Generated",
    "SchemaVersionMetadata.cs"
  ),
];
const VERSIONS = {
  min: "0.6.0-alpha",
  maxSupported: "0.10.0-alpha",
  stateAware: "0.9.0-alpha",
  stateAwareWindowsSandbox: "0.10.0-alpha",
  stateAwareWslc: "0.9.0-alpha",
  stableLatest: "0.9.0-alpha",
};

function write(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function createFixture(versions = VERSIONS) {
  const root = mkdtempSync(join(tmpdir(), "schema-version-metadata-"));
  write(
    join(root, "schemas", "schema-version.json"),
    `${JSON.stringify(versions, null, 2)}\n`
  );
  return root;
}

function run(root, ...args) {
  const stdout = [];
  const stderr = [];
  const status = runGenerator({
    repoRoot: root,
    args,
    stdout: message => stdout.push(message),
    stderr: message => stderr.push(message),
  });
  return {
    status,
    output: [...stdout, ...stderr].join("\n"),
  };
}

function generated(root) {
  return new Map(
    OUTPUTS.map(path => [path, readFileSync(join(root, path), "utf8")])
  );
}

test("generation is deterministic and emits LF-only metadata", () => {
  const root = createFixture();
  try {
    const first = run(root);
    assert.equal(first.status, 0, first.output);
    const firstOutput = generated(root);

    const second = run(root);
    assert.equal(second.status, 0, second.output);
    assert.deepEqual(generated(root), firstOutput);

    assert.match(
      firstOutput.get(OUTPUTS[0]),
      /ContainmentBackend::WindowsSandbox => Some\(ContractVersion::V0_10_0Alpha\)/
    );
    assert.match(
      firstOutput.get(OUTPUTS[1]),
      /WINDOWS_SANDBOX_STATE_AWARE_VERSION = '0\.10\.0-alpha'/
    );
    assert.match(
      firstOutput.get(OUTPUTS[2]),
      /WindowsSandboxStateAware = "0\.10\.0-alpha"/
    );
    for (const content of firstOutput.values()) {
      assert.doesNotMatch(content, /\r\n/);
      assert.match(
        content,
        /@generated by scripts\/versioning\/generate-schema-version-metadata\.js/
      );
    }
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("--check accepts up-to-date metadata", () => {
  const root = createFixture();
  try {
    assert.equal(run(root).status, 0);
    const result = run(root, "--check");
    assert.equal(result.status, 0, result.output);
    assert.match(result.output, /metadata is current/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("--check rejects stale metadata", () => {
  const root = createFixture();
  try {
    assert.equal(run(root).status, 0);
    write(join(root, OUTPUTS[0]), "stale\n");

    const result = run(root, "--check");
    assert.equal(result.status, 1, result.output);
    assert.match(result.output, /metadata is stale/);
    assert.match(result.output, /Run node scripts\/versioning\/generate-schema-version-metadata\.js/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("--check rejects a missing output", () => {
  const root = createFixture();
  try {
    const result = run(root, "--check");
    assert.equal(result.status, 1, result.output);
    assert.match(result.output, /Missing generated schema-version metadata/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generation rejects a malformed canonical contract version", () => {
  const root = createFixture({
    ...VERSIONS,
    stateAware: "not-a-contract-version",
  });
  try {
    const result = run(root);
    assert.equal(result.status, 1, result.output);
    assert.match(result.output, /cannot map contract version "not-a-contract-version"/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generation rejects unknown arguments", () => {
  const root = createFixture();
  try {
    const result = run(root, "--unknown");
    assert.equal(result.status, 2, result.output);
    assert.match(result.output, /Unknown argument\(s\): --unknown/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
