// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! C# emitter for the SDK wire types.
//!
//! Walks an exact contract's generated JSON Schema as a `serde_json::Value` and
//! emits internal System.Text.Json models for the .NET SDK. The emitter is
//! deliberately small and supports only the schema constructs exact MXC
//! contracts use: closed object definitions, string enums, `$ref`, nullable
//! wrappers, arrays, scalar types, and root dispatch schemas whose request roots
//! are named definitions.

use std::collections::{BTreeMap, BTreeSet};

use serde_json::Value;

#[cfg(test)]
const TEST_BANNER: &str = "\
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// GENERATED TEST OUTPUT.

#nullable enable

using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace Microsoft.Mxc.Sdk.Generated;

";

pub(crate) fn emit_contract_cs(schema: &Value, version: &str) -> String {
    let module_version = version.replace(['.', '-'], "_");
    let banner = format!(
        "\
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// <auto-generated>
// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Emitted from the exact MXC {version} contract by mxc_schema_gen. These are
// internal SDK wire types, not public API.
//
// Regenerate with:
//   cargo run --manifest-path src/Cargo.toml -p mxc_schema_gen -- csharp --version {version} --out sdk/dotnet/Microsoft.Mxc.Sdk/Generated/MxcConfigV{module_version}.g.cs
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace Microsoft.Mxc.Sdk.Generated;

"
    );
    let mut output = emit_cs_with_banner(schema, &banner);
    while output.ends_with("\n\n") {
        output.pop();
    }
    output
}

#[cfg(test)]
pub(crate) fn emit_cs(schema: &Value) -> String {
    emit_cs_with_banner(schema, TEST_BANNER)
}

fn emit_cs_with_banner(schema: &Value, banner: &str) -> String {
    let root = schema.as_object().expect("schema root is an object");
    let definitions = root
        .get("definitions")
        .and_then(Value::as_object)
        .expect("schema definitions object");
    let definition_kinds = definition_kinds(definitions);
    let mut out = String::from(banner);

    for (name, definition) in definitions {
        emit_definition(&mut out, name, definition, definitions, &definition_kinds);
    }

    out
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum DefinitionKind {
    Object,
    StringEnum,
    Scalar,
    Unknown,
}

fn definition_kinds(
    definitions: &serde_json::Map<String, Value>,
) -> BTreeMap<String, DefinitionKind> {
    definitions
        .iter()
        .map(|(name, definition)| {
            let kind = definition
                .as_object()
                .map(|object| {
                    if string_enum_variants(object).is_some() {
                        DefinitionKind::StringEnum
                    } else if object.get("type").and_then(Value::as_str) == Some("object") {
                        DefinitionKind::Object
                    } else {
                        scalar_definition_kind(object)
                    }
                })
                .unwrap_or(DefinitionKind::Unknown);
            (name.clone(), kind)
        })
        .collect()
}

fn scalar_definition_kind(object: &serde_json::Map<String, Value>) -> DefinitionKind {
    if object.contains_key("$ref")
        || object.contains_key("anyOf")
        || object.contains_key("oneOf")
        || object.contains_key("type")
    {
        DefinitionKind::Scalar
    } else {
        DefinitionKind::Unknown
    }
}

fn emit_definition(
    out: &mut String,
    name: &str,
    definition: &Value,
    definitions: &serde_json::Map<String, Value>,
    definition_kinds: &BTreeMap<String, DefinitionKind>,
) {
    let Some(object) = definition.as_object() else {
        return;
    };

    if let Some(variants) = string_enum_variants(object) {
        emit_string_enum(out, name, object.get("description"), &variants);
        return;
    }

    if object.get("type").and_then(Value::as_str) == Some("object") {
        emit_object(out, name, object, definitions, definition_kinds);
    }
}

fn emit_string_enum(
    out: &mut String,
    name: &str,
    description: Option<&Value>,
    variants: &[String],
) {
    push_doc(out, description);
    out.push_str(&format!("internal static class {name}\n{{\n"));
    let mut used = BTreeSet::new();
    for value in variants {
        let base = pascal_identifier(value);
        let mut member = base.clone();
        let mut index = 2;
        while !used.insert(member.clone()) {
            member = format!("{base}{index}");
            index += 1;
        }
        let literal = serde_json::to_string(value).expect("enum string serializes");
        out.push_str(&format!("    public const string {member} = {literal};\n"));
    }
    out.push_str("}\n\n");
}

fn emit_object(
    out: &mut String,
    name: &str,
    object: &serde_json::Map<String, Value>,
    definitions: &serde_json::Map<String, Value>,
    definition_kinds: &BTreeMap<String, DefinitionKind>,
) {
    push_doc(out, object.get("description"));
    out.push_str(&format!("internal sealed class {name}\n{{\n"));

    let required = object
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();

    if let Some(properties) = object.get("properties").and_then(Value::as_object) {
        for (json_name, property) in properties {
            let optional = !required.contains(json_name.as_str());
            let (base, nullable) = cs_type_inner(property, definitions, definition_kinds);
            let ty = if optional || nullable {
                nullable_type(&base)
            } else {
                base
            };
            let property_name = pascal_identifier(json_name);
            push_field_doc(out, property.get("description"));
            out.push_str(&format!("    [JsonPropertyName(\"{json_name}\")]\n"));
            if optional {
                out.push_str("    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n");
            } else if nullable {
                out.push_str("    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]\n");
            }
            let initializer = initializer(&ty, optional);
            out.push_str(&format!(
                "    public {ty} {property_name} {{ get; set; }}{initializer}\n\n"
            ));
        }
    }

    out.push_str("}\n\n");
}

fn initializer(ty: &str, optional: bool) -> &'static str {
    if optional {
        return "";
    }
    if ty == "string" {
        " = string.Empty;"
    } else if ty.starts_with("List<")
        || ty == "object"
        || (!ty.ends_with('?') && ty.chars().next().is_some_and(char::is_uppercase))
    {
        " = new();"
    } else {
        ""
    }
}

fn cs_type_inner(
    schema: &Value,
    definitions: &serde_json::Map<String, Value>,
    definition_kinds: &BTreeMap<String, DefinitionKind>,
) -> (String, bool) {
    let Some(object) = schema.as_object() else {
        return ("object".to_string(), false);
    };

    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        let name = ref_name(reference);
        return match definition_kinds.get(&name) {
            Some(DefinitionKind::Object) => (name, false),
            Some(DefinitionKind::StringEnum) => ("string".to_string(), false),
            Some(DefinitionKind::Scalar) => definitions
                .get(&name)
                .map(|definition| cs_type_inner(definition, definitions, definition_kinds))
                .unwrap_or_else(|| ("object".to_string(), false)),
            _ => ("object".to_string(), false),
        };
    }

    if string_enum_variants(object).is_some() {
        return ("string".to_string(), false);
    }

    if let Some(any_of) = object.get("anyOf").and_then(Value::as_array) {
        let mut nullable = false;
        let mut types = Vec::new();
        for branch in any_of {
            if is_null_schema(branch) {
                nullable = true;
                continue;
            }
            let (ty, branch_nullable) = cs_type_inner(branch, definitions, definition_kinds);
            nullable |= branch_nullable;
            if !types.contains(&ty) {
                types.push(ty);
            }
        }
        return match types.as_slice() {
            [only] => (only.clone(), nullable),
            _ => ("object".to_string(), nullable),
        };
    }

    if let Some(one_of) = object.get("oneOf").and_then(Value::as_array) {
        if string_enum_variants(object).is_some() {
            return ("string".to_string(), false);
        }
        let mut types = Vec::new();
        let mut nullable = false;
        for branch in one_of {
            if is_null_schema(branch) {
                nullable = true;
                continue;
            }
            let (ty, branch_nullable) = cs_type_inner(branch, definitions, definition_kinds);
            nullable |= branch_nullable;
            if !types.contains(&ty) {
                types.push(ty);
            }
        }
        return match types.as_slice() {
            [only] => (only.clone(), nullable),
            _ => ("object".to_string(), nullable),
        };
    }

    match object.get("type") {
        Some(Value::String(ty)) => (
            scalar_type(ty, object, definitions, definition_kinds),
            false,
        ),
        Some(Value::Array(types)) => {
            let mut nullable = false;
            let mut base = "object".to_string();
            for ty in types {
                match ty.as_str() {
                    Some("null") => nullable = true,
                    Some(name) => base = scalar_type(name, object, definitions, definition_kinds),
                    None => {}
                }
            }
            (base, nullable)
        }
        _ => ("object".to_string(), false),
    }
}

fn scalar_type(
    ty: &str,
    object: &serde_json::Map<String, Value>,
    definitions: &serde_json::Map<String, Value>,
    definition_kinds: &BTreeMap<String, DefinitionKind>,
) -> String {
    match ty {
        "string" => "string".to_string(),
        "integer" => integer_type(object),
        "number" => "double".to_string(),
        "boolean" => "bool".to_string(),
        "array" => {
            let items = object.get("items").unwrap_or(&Value::Null);
            let (item, _) = cs_type_inner(items, definitions, definition_kinds);
            format!("List<{}>", nullable_type(&item).trim_end_matches('?'))
        }
        "object" => "Dictionary<string, object?>".to_string(),
        _ => "object".to_string(),
    }
}

fn integer_type(object: &serde_json::Map<String, Value>) -> String {
    let minimum = object.get("minimum");
    let maximum = object.get("maximum");
    match minimum {
        Some(min) if nonnegative_integral_bound(min) => {
            if maximum.is_some_and(|max| integral_bound_at_most(max, u16::MAX.into())) {
                "ushort"
            } else if maximum.is_some_and(|max| integral_bound_at_most(max, u32::MAX.into())) {
                "uint"
            } else {
                "ulong"
            }
        }
        _ => "long",
    }
    .to_string()
}

fn nonnegative_integral_bound(value: &Value) -> bool {
    value.as_u64().is_some()
        || value
            .as_f64()
            .is_some_and(|number| number.is_finite() && number >= 0.0 && number.fract() == 0.0)
}

fn integral_bound_at_most(value: &Value, maximum: u64) -> bool {
    value.as_u64().is_some_and(|number| number <= maximum)
        || value.as_f64().is_some_and(|number| {
            number.is_finite() && number >= 0.0 && number.fract() == 0.0 && number <= maximum as f64
        })
}

fn nullable_type(ty: &str) -> String {
    match ty {
        "bool" | "ushort" | "uint" | "ulong" | "long" | "double" => format!("{ty}?"),
        _ if ty.ends_with('?') => ty.to_string(),
        _ => format!("{ty}?"),
    }
}

fn string_enum_variants(object: &serde_json::Map<String, Value>) -> Option<Vec<String>> {
    if let Some(one_of) = object.get("oneOf").and_then(Value::as_array) {
        let mut variants = Vec::new();
        for branch in one_of {
            let branch = branch.as_object()?;
            let enum_values = branch.get("enum")?.as_array()?;
            let value = enum_values.first()?.as_str()?;
            variants.push(value.to_string());
        }
        return Some(variants);
    }

    if let Some(enum_values) = object.get("enum").and_then(Value::as_array) {
        let variants = enum_values
            .iter()
            .map(Value::as_str)
            .collect::<Option<Vec<_>>>()?;
        if !variants.is_empty() {
            return Some(variants.into_iter().map(str::to_string).collect());
        }
    }

    None
}

fn ref_name(reference: &str) -> String {
    reference
        .rsplit('/')
        .next()
        .unwrap_or(reference)
        .to_string()
}

fn is_null_schema(value: &Value) -> bool {
    value.get("type").and_then(Value::as_str) == Some("null")
}

fn pascal_identifier(name: &str) -> String {
    let trimmed = name.trim_start_matches(['$', '_']);
    let mut output = String::new();
    let mut upper = true;
    for character in trimmed.chars() {
        if character.is_ascii_alphanumeric() {
            if output.is_empty() && character.is_ascii_digit() {
                output.push('_');
            }
            if upper {
                output.push(character.to_ascii_uppercase());
            } else {
                output.push(character);
            }
            upper = false;
        } else {
            upper = true;
        }
    }
    if output.is_empty() {
        "Value".to_string()
    } else {
        output
    }
}

fn push_doc(out: &mut String, description: Option<&Value>) {
    push_indented_doc(out, "", description);
}

fn push_field_doc(out: &mut String, description: Option<&Value>) {
    push_indented_doc(out, "    ", description);
}

fn push_indented_doc(out: &mut String, indent: &str, description: Option<&Value>) {
    if let Some(text) = description.and_then(Value::as_str) {
        out.push_str(indent);
        out.push_str("/// <summary>\n");
        for line in doc_lines(text) {
            out.push_str(indent);
            out.push_str("///");
            if !line.is_empty() {
                out.push(' ');
                out.push_str(&xml_escape(&line));
            }
            out.push('\n');
        }
        out.push_str(indent);
        out.push_str("/// </summary>\n");
    }
}

fn doc_lines(text: &str) -> Vec<String> {
    text.replace("*/", "* /")
        .lines()
        .map(|line| line.trim_end().to_string())
        .collect()
}

fn xml_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn emits_internal_classes_with_nullable_optional_properties() {
        let schema = json!({
            "definitions": {
                "Thing": {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["name"],
                    "properties": {
                        "name": { "type": "string" },
                        "count": { "type": "integer", "minimum": 0, "maximum": 65535 },
                        "child": {
                            "anyOf": [
                                { "$ref": "#/definitions/Thing" },
                                { "type": "null" }
                            ]
                        }
                    }
                }
            }
        });

        let cs = emit_cs(&schema);

        assert!(cs.contains("internal sealed class Thing"), "{cs}");
        assert!(
            cs.contains("public string Name { get; set; } = string.Empty;"),
            "{cs}"
        );
        assert!(cs.contains("public ushort? Count { get; set; }"), "{cs}");
        assert!(cs.contains("public Thing? Child { get; set; }"), "{cs}");
        assert!(
            cs.contains("[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]"),
            "{cs}"
        );
    }

    #[test]
    fn required_nullable_property_is_emitted_even_with_global_null_omission() {
        let schema = json!({
            "definitions": {
                "Thing": {
                    "type": "object",
                    "required": ["nullableChild"],
                    "properties": {
                        "nullableChild": {
                            "anyOf": [
                                { "type": "string" },
                                { "type": "null" }
                            ]
                        },
                        "optionalChild": {
                            "anyOf": [
                                { "type": "string" },
                                { "type": "null" }
                            ]
                        }
                    }
                }
            }
        });

        let cs = emit_cs(&schema);
        assert!(
            cs.contains(
                "[JsonPropertyName(\"nullableChild\")]\n    \
                 [JsonIgnore(Condition = JsonIgnoreCondition.Never)]\n    \
                 public string? NullableChild"
            ),
            "{cs}"
        );
        assert!(
            cs.contains(
                "[JsonPropertyName(\"optionalChild\")]\n    \
                 [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n    \
                 public string? OptionalChild"
            ),
            "{cs}"
        );
    }

    #[test]
    fn integer_bounds_preserve_unsigned_types_across_numeric_representations() {
        for (minimum, maximum, expected) in [
            (json!(0), json!(65535), "ushort"),
            (json!(0.0), json!(65535.0), "ushort"),
            (json!(0.0), json!(65536.0), "uint"),
            (json!(0.0), json!(4294967295.0), "uint"),
            (json!(0.0), json!(4294967296.0), "ulong"),
            (json!(0.0), json!(u64::MAX), "ulong"),
            (json!(-1.0), json!(65535.0), "long"),
        ] {
            let schema = json!({
                "definitions": {
                    "Thing": {
                        "type": "object",
                        "properties": {
                            "limit": {
                                "type": "integer",
                                "minimum": minimum,
                                "maximum": maximum
                            }
                        }
                    }
                }
            });
            let cs = emit_cs(&schema);
            assert!(
                cs.contains(&format!("public {expected}? Limit {{ get; set; }}")),
                "unexpected type for {minimum}..={maximum}: {cs}"
            );
        }
    }

    #[test]
    fn emits_string_enum_constants() {
        let schema = json!({
            "definitions": {
                "Containment": {
                    "oneOf": [
                        { "type": "string", "enum": ["process"] },
                        { "type": "string", "enum": ["processcontainer"] },
                        { "type": "string", "enum": ["isolation_session"] }
                    ]
                }
            }
        });

        let cs = emit_cs(&schema);

        assert!(cs.contains("internal static class Containment"), "{cs}");
        assert!(
            cs.contains("public const string Process = \"process\";"),
            "{cs}"
        );
        assert!(
            cs.contains("public const string IsolationSession = \"isolation_session\";"),
            "{cs}"
        );
    }

    #[test]
    fn contract_output_has_one_terminal_newline() {
        let schema = json!({ "definitions": {} });

        let cs = emit_contract_cs(&schema, "1.0.0");

        assert!(cs.ends_with('\n'));
        assert!(!cs.ends_with("\n\n"));
    }

    #[test]
    fn blank_doc_lines_have_no_trailing_whitespace() {
        let schema = json!({
            "definitions": {
                "Thing": {
                    "description": "First paragraph.\n\nSecond paragraph.",
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "name": {
                            "description": "One.\n\nTwo.",
                            "type": "string"
                        }
                    }
                }
            }
        });

        let cs = emit_cs(&schema);

        assert!(cs.contains("\n///\n"), "{cs}");
        assert!(cs.contains("\n    ///\n"), "{cs}");
        for line in cs.lines() {
            assert_eq!(line, line.trim_end(), "trailing whitespace: {line:?}");
        }
    }
}
