<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Mxc.Samples.WslcStateAware</RootNamespace>
    <AssemblyName>mxc-wslc-state-aware-sample</AssemblyName>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <MxcWithWslc>true</MxcWithWslc>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sdk\dotnet\Microsoft.Mxc.Sdk\Microsoft.Mxc.Sdk.csproj">
      <AdditionalProperties>MxcWithWslc=true</AdditionalProperties>
    </ProjectReference>
  </ItemGroup>

</Project>
