[package]
name = "wxc_winhttp_proxy_shim"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "winhttp-proxy-shim"
path = "src/main.rs"

[dependencies]
mxc-sdk.workspace = true
clap.workspace = true
windows.workspace = true
windows-core.workspace = true

[target.'cfg(windows)'.build-dependencies]
cc = "1"
winresource.workspace = true
