// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum DestinationRuleOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DestinationRule<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DestinationRule<'a> {
    type Inner = DestinationRule<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> DestinationRule<'a> {
    pub const VT_SUBNET: ::flatbuffers::VOffsetT = 4;
    pub const VT_EXCEPT: ::flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        DestinationRule { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args DestinationRuleArgs<'args>,
    ) -> ::flatbuffers::WIPOffset<DestinationRule<'bldr>> {
        let mut builder = DestinationRuleBuilder::new(_fbb);
        if let Some(x) = args.except {
            builder.add_except(x);
        }
        if let Some(x) = args.subnet {
            builder.add_subnet(x);
        }
        builder.finish()
    }

    pub fn unpack(&self) -> DestinationRuleT {
        let subnet = self.subnet().map(|x| alloc::boxed::Box::new(x.unpack()));
        let except = self
            .except()
            .map(|x| x.iter().map(|t| t.unpack()).collect());
        DestinationRuleT { subnet, except }
    }

    #[inline]
    pub fn subnet(&self) -> Option<IpSubnet<'a>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<IpSubnet>>(DestinationRule::VT_SUBNET, None)
        }
    }
    #[inline]
    pub fn except(
        &self,
    ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IpSubnet<'a>>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IpSubnet>>,
            >>(DestinationRule::VT_EXCEPT, None)
        }
    }
}

impl ::flatbuffers::Verifiable for DestinationRule<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<::flatbuffers::ForwardsUOffset<IpSubnet>>(
                "subnet",
                Self::VT_SUBNET,
                false,
            )?
            .visit_field::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<IpSubnet>>,
            >>("except", Self::VT_EXCEPT, false)?
            .finish();
        Ok(())
    }
}
pub struct DestinationRuleArgs<'a> {
    pub subnet: Option<::flatbuffers::WIPOffset<IpSubnet<'a>>>,
    pub except: Option<
        ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IpSubnet<'a>>>,
        >,
    >,
}
impl<'a> Default for DestinationRuleArgs<'a> {
    #[inline]
    fn default() -> Self {
        DestinationRuleArgs {
            subnet: None,
            except: None,
        }
    }
}

pub struct DestinationRuleBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DestinationRuleBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_subnet(&mut self, subnet: ::flatbuffers::WIPOffset<IpSubnet<'b>>) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<IpSubnet>>(
                DestinationRule::VT_SUBNET,
                subnet,
            );
    }
    #[inline]
    pub fn add_except(
        &mut self,
        except: ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<IpSubnet<'b>>>,
        >,
    ) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(DestinationRule::VT_EXCEPT, except);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> DestinationRuleBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        DestinationRuleBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<DestinationRule<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for DestinationRule<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("DestinationRule");
        ds.field("subnet", &self.subnet());
        ds.field("except", &self.except());
        ds.finish()
    }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct DestinationRuleT {
    pub subnet: Option<alloc::boxed::Box<IpSubnetT>>,
    pub except: Option<alloc::vec::Vec<IpSubnetT>>,
}
impl Default for DestinationRuleT {
    fn default() -> Self {
        Self {
            subnet: None,
            except: None,
        }
    }
}
impl DestinationRuleT {
    pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
        &self,
        _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>,
    ) -> ::flatbuffers::WIPOffset<DestinationRule<'b>> {
        let subnet = self.subnet.as_ref().map(|x| x.pack(_fbb));
        let except = self.except.as_ref().map(|x| {
            let w: alloc::vec::Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();
            _fbb.create_vector(&w)
        });
        DestinationRule::create(_fbb, &DestinationRuleArgs { subnet, except })
    }
}
