// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum EndpointRuleOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EndpointRule<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for EndpointRule<'a> {
    type Inner = EndpointRule<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> EndpointRule<'a> {
    pub const VT_DESTINATIONS: ::flatbuffers::VOffsetT = 4;
    pub const VT_PORTS: ::flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        EndpointRule { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args EndpointRuleArgs<'args>,
    ) -> ::flatbuffers::WIPOffset<EndpointRule<'bldr>> {
        let mut builder = EndpointRuleBuilder::new(_fbb);
        if let Some(x) = args.ports {
            builder.add_ports(x);
        }
        if let Some(x) = args.destinations {
            builder.add_destinations(x);
        }
        builder.finish()
    }

    pub fn unpack(&self) -> EndpointRuleT {
        let destinations = self
            .destinations()
            .map(|x| x.iter().map(|t| t.unpack()).collect());
        let ports = self.ports().map(|x| x.iter().map(|t| t.unpack()).collect());
        EndpointRuleT {
            destinations,
            ports,
        }
    }

    #[inline]
    pub fn destinations(
        &self,
    ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DestinationRule<'a>>>>
    {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DestinationRule>>,
            >>(EndpointRule::VT_DESTINATIONS, None)
        }
    }
    #[inline]
    pub fn ports(
        &self,
    ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PortRule<'a>>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PortRule>>,
            >>(EndpointRule::VT_PORTS, None)
        }
    }
}

impl ::flatbuffers::Verifiable for EndpointRule<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<DestinationRule>>,
            >>("destinations", Self::VT_DESTINATIONS, false)?
            .visit_field::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<PortRule>>,
            >>("ports", Self::VT_PORTS, false)?
            .finish();
        Ok(())
    }
}
pub struct EndpointRuleArgs<'a> {
    pub destinations: Option<
        ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DestinationRule<'a>>>,
        >,
    >,
    pub ports: Option<
        ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PortRule<'a>>>,
        >,
    >,
}
impl<'a> Default for EndpointRuleArgs<'a> {
    #[inline]
    fn default() -> Self {
        EndpointRuleArgs {
            destinations: None,
            ports: None,
        }
    }
}

pub struct EndpointRuleBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EndpointRuleBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_destinations(
        &mut self,
        destinations: ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<DestinationRule<'b>>>,
        >,
    ) {
        self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
            EndpointRule::VT_DESTINATIONS,
            destinations,
        );
    }
    #[inline]
    pub fn add_ports(
        &mut self,
        ports: ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<PortRule<'b>>>,
        >,
    ) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(EndpointRule::VT_PORTS, ports);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> EndpointRuleBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        EndpointRuleBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<EndpointRule<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for EndpointRule<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("EndpointRule");
        ds.field("destinations", &self.destinations());
        ds.field("ports", &self.ports());
        ds.finish()
    }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct EndpointRuleT {
    pub destinations: Option<alloc::vec::Vec<DestinationRuleT>>,
    pub ports: Option<alloc::vec::Vec<PortRuleT>>,
}
impl Default for EndpointRuleT {
    fn default() -> Self {
        Self {
            destinations: None,
            ports: None,
        }
    }
}
impl EndpointRuleT {
    pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
        &self,
        _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>,
    ) -> ::flatbuffers::WIPOffset<EndpointRule<'b>> {
        let destinations = self.destinations.as_ref().map(|x| {
            let w: alloc::vec::Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();
            _fbb.create_vector(&w)
        });
        let ports = self.ports.as_ref().map(|x| {
            let w: alloc::vec::Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();
            _fbb.create_vector(&w)
        });
        EndpointRule::create(
            _fbb,
            &EndpointRuleArgs {
                destinations,
                ports,
            },
        )
    }
}
