// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum EndpointPolicyOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EndpointPolicy<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for EndpointPolicy<'a> {
    type Inner = EndpointPolicy<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> EndpointPolicy<'a> {
    pub const VT_DEFAULT_ACTION: ::flatbuffers::VOffsetT = 4;
    pub const VT_ALLOW: ::flatbuffers::VOffsetT = 6;
    pub const VT_DENY: ::flatbuffers::VOffsetT = 8;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        EndpointPolicy { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args EndpointPolicyArgs<'args>,
    ) -> ::flatbuffers::WIPOffset<EndpointPolicy<'bldr>> {
        let mut builder = EndpointPolicyBuilder::new(_fbb);
        if let Some(x) = args.deny {
            builder.add_deny(x);
        }
        if let Some(x) = args.allow {
            builder.add_allow(x);
        }
        builder.add_default_action(args.default_action);
        builder.finish()
    }

    pub fn unpack(&self) -> EndpointPolicyT {
        let default_action = self.default_action();
        let allow = self.allow().map(|x| x.iter().map(|t| t.unpack()).collect());
        let deny = self.deny().map(|x| x.iter().map(|t| t.unpack()).collect());
        EndpointPolicyT {
            default_action,
            allow,
            deny,
        }
    }

    #[inline]
    pub fn default_action(&self) -> FilterAction {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<FilterAction>(EndpointPolicy::VT_DEFAULT_ACTION, Some(FilterAction::deny))
                .unwrap()
        }
    }
    #[inline]
    pub fn allow(
        &self,
    ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<EndpointRule<'a>>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<EndpointRule>>,
            >>(EndpointPolicy::VT_ALLOW, None)
        }
    }
    #[inline]
    pub fn deny(
        &self,
    ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<EndpointRule<'a>>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<EndpointRule>>,
            >>(EndpointPolicy::VT_DENY, None)
        }
    }
}

impl ::flatbuffers::Verifiable for EndpointPolicy<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<FilterAction>("default_action", Self::VT_DEFAULT_ACTION, false)?
            .visit_field::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<EndpointRule>>,
            >>("allow", Self::VT_ALLOW, false)?
            .visit_field::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<EndpointRule>>,
            >>("deny", Self::VT_DENY, false)?
            .finish();
        Ok(())
    }
}
pub struct EndpointPolicyArgs<'a> {
    pub default_action: FilterAction,
    pub allow: Option<
        ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<EndpointRule<'a>>>,
        >,
    >,
    pub deny: Option<
        ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<EndpointRule<'a>>>,
        >,
    >,
}
impl<'a> Default for EndpointPolicyArgs<'a> {
    #[inline]
    fn default() -> Self {
        EndpointPolicyArgs {
            default_action: FilterAction::deny,
            allow: None,
            deny: None,
        }
    }
}

pub struct EndpointPolicyBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EndpointPolicyBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_default_action(&mut self, default_action: FilterAction) {
        self.fbb_.push_slot::<FilterAction>(
            EndpointPolicy::VT_DEFAULT_ACTION,
            default_action,
            FilterAction::deny,
        );
    }
    #[inline]
    pub fn add_allow(
        &mut self,
        allow: ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<EndpointRule<'b>>>,
        >,
    ) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(EndpointPolicy::VT_ALLOW, allow);
    }
    #[inline]
    pub fn add_deny(
        &mut self,
        deny: ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<EndpointRule<'b>>>,
        >,
    ) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(EndpointPolicy::VT_DENY, deny);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> EndpointPolicyBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        EndpointPolicyBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<EndpointPolicy<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for EndpointPolicy<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("EndpointPolicy");
        ds.field("default_action", &self.default_action());
        ds.field("allow", &self.allow());
        ds.field("deny", &self.deny());
        ds.finish()
    }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct EndpointPolicyT {
    pub default_action: FilterAction,
    pub allow: Option<alloc::vec::Vec<EndpointRuleT>>,
    pub deny: Option<alloc::vec::Vec<EndpointRuleT>>,
}
impl Default for EndpointPolicyT {
    fn default() -> Self {
        Self {
            default_action: FilterAction::deny,
            allow: None,
            deny: None,
        }
    }
}
impl EndpointPolicyT {
    pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
        &self,
        _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>,
    ) -> ::flatbuffers::WIPOffset<EndpointPolicy<'b>> {
        let default_action = self.default_action;
        let allow = self.allow.as_ref().map(|x| {
            let w: alloc::vec::Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();
            _fbb.create_vector(&w)
        });
        let deny = self.deny.as_ref().map(|x| {
            let w: alloc::vec::Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();
            _fbb.create_vector(&w)
        });
        EndpointPolicy::create(
            _fbb,
            &EndpointPolicyArgs {
                default_action,
                allow,
                deny,
            },
        )
    }
}
