// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IngressPolicyOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IngressPolicy<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IngressPolicy<'a> {
    type Inner = IngressPolicy<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IngressPolicy<'a> {
    pub const VT_DEFAULT_ACTION: ::flatbuffers::VOffsetT = 4;
    pub const VT_HOST_LOOPBACK: ::flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IngressPolicy { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IngressPolicyArgs,
    ) -> ::flatbuffers::WIPOffset<IngressPolicy<'bldr>> {
        let mut builder = IngressPolicyBuilder::new(_fbb);
        builder.add_host_loopback(args.host_loopback);
        builder.add_default_action(args.default_action);
        builder.finish()
    }

    pub fn unpack(&self) -> IngressPolicyT {
        let default_action = self.default_action();
        let host_loopback = self.host_loopback();
        IngressPolicyT {
            default_action,
            host_loopback,
        }
    }

    #[inline]
    pub fn default_action(&self) -> FilterAction {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<FilterAction>(IngressPolicy::VT_DEFAULT_ACTION, Some(FilterAction::deny))
                .unwrap()
        }
    }
    #[inline]
    pub fn host_loopback(&self) -> FilterAction {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<FilterAction>(IngressPolicy::VT_HOST_LOOPBACK, Some(FilterAction::deny))
                .unwrap()
        }
    }
}

impl ::flatbuffers::Verifiable for IngressPolicy<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<FilterAction>("default_action", Self::VT_DEFAULT_ACTION, false)?
            .visit_field::<FilterAction>("host_loopback", Self::VT_HOST_LOOPBACK, false)?
            .finish();
        Ok(())
    }
}
pub struct IngressPolicyArgs {
    pub default_action: FilterAction,
    pub host_loopback: FilterAction,
}
impl<'a> Default for IngressPolicyArgs {
    #[inline]
    fn default() -> Self {
        IngressPolicyArgs {
            default_action: FilterAction::deny,
            host_loopback: FilterAction::deny,
        }
    }
}

pub struct IngressPolicyBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IngressPolicyBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_default_action(&mut self, default_action: FilterAction) {
        self.fbb_.push_slot::<FilterAction>(
            IngressPolicy::VT_DEFAULT_ACTION,
            default_action,
            FilterAction::deny,
        );
    }
    #[inline]
    pub fn add_host_loopback(&mut self, host_loopback: FilterAction) {
        self.fbb_.push_slot::<FilterAction>(
            IngressPolicy::VT_HOST_LOOPBACK,
            host_loopback,
            FilterAction::deny,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IngressPolicyBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IngressPolicyBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IngressPolicy<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IngressPolicy<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IngressPolicy");
        ds.field("default_action", &self.default_action());
        ds.field("host_loopback", &self.host_loopback());
        ds.finish()
    }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct IngressPolicyT {
    pub default_action: FilterAction,
    pub host_loopback: FilterAction,
}
impl Default for IngressPolicyT {
    fn default() -> Self {
        Self {
            default_action: FilterAction::deny,
            host_loopback: FilterAction::deny,
        }
    }
}
impl IngressPolicyT {
    pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
        &self,
        _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>,
    ) -> ::flatbuffers::WIPOffset<IngressPolicy<'b>> {
        let default_action = self.default_action;
        let host_loopback = self.host_loopback;
        IngressPolicy::create(
            _fbb,
            &IngressPolicyArgs {
                default_action,
                host_loopback,
            },
        )
    }
}
