// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MIN_IP_PROTOCOL: i8 = 0;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MAX_IP_PROTOCOL: i8 = 4;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_IP_PROTOCOL: [IpProtocol; 5] = [
    IpProtocol::any,
    IpProtocol::tcp,
    IpProtocol::udp,
    IpProtocol::icmpv4,
    IpProtocol::icmpv6,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct IpProtocol(pub i8);
#[allow(non_upper_case_globals)]
impl IpProtocol {
    pub const any: Self = Self(0);
    pub const tcp: Self = Self(1);
    pub const udp: Self = Self(2);
    pub const icmpv4: Self = Self(3);
    pub const icmpv6: Self = Self(4);

    pub const ENUM_MIN: i8 = 0;
    pub const ENUM_MAX: i8 = 4;
    pub const ENUM_VALUES: &'static [Self] =
        &[Self::any, Self::tcp, Self::udp, Self::icmpv4, Self::icmpv6];
    /// Returns the variant's name or "" if unknown.
    pub fn variant_name(self) -> Option<&'static str> {
        match self {
            Self::any => Some("any"),
            Self::tcp => Some("tcp"),
            Self::udp => Some("udp"),
            Self::icmpv4 => Some("icmpv4"),
            Self::icmpv6 => Some("icmpv6"),
            _ => None,
        }
    }
}
impl ::core::fmt::Debug for IpProtocol {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        if let Some(name) = self.variant_name() {
            f.write_str(name)
        } else {
            f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
        }
    }
}
impl<'a> ::flatbuffers::Follow<'a> for IpProtocol {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
        Self(b)
    }
}

impl ::flatbuffers::Push for IpProtocol {
    type Output = IpProtocol;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for IpProtocol {
    type Scalar = i8;
    #[inline]
    fn to_little_endian(self) -> i8 {
        self.0.to_le()
    }
    #[inline]
    #[allow(clippy::wrong_self_convention)]
    fn from_little_endian(v: i8) -> Self {
        let b = i8::from_le(v);
        Self(b)
    }
}

impl<'a> ::flatbuffers::Verifiable for IpProtocol {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        i8::run_verifier(v, pos)
    }
}

impl ::flatbuffers::SimpleToVerifyInSlice for IpProtocol {}
