// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum ProxyInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ProxyInfo<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ProxyInfo<'a> {
    type Inner = ProxyInfo<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> ProxyInfo<'a> {
    pub const VT_URL: ::flatbuffers::VOffsetT = 4;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        ProxyInfo { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args ProxyInfoArgs<'args>,
    ) -> ::flatbuffers::WIPOffset<ProxyInfo<'bldr>> {
        let mut builder = ProxyInfoBuilder::new(_fbb);
        if let Some(x) = args.url {
            builder.add_url(x);
        }
        builder.finish()
    }

    pub fn unpack(&self) -> ProxyInfoT {
        let url = self.url().map(|x| alloc::string::ToString::to_string(x));
        ProxyInfoT { url }
    }

    #[inline]
    pub fn url(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<&str>>(ProxyInfo::VT_URL, None)
        }
    }
}

impl ::flatbuffers::Verifiable for ProxyInfo<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("url", Self::VT_URL, false)?
            .finish();
        Ok(())
    }
}
pub struct ProxyInfoArgs<'a> {
    pub url: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ProxyInfoArgs<'a> {
    #[inline]
    fn default() -> Self {
        ProxyInfoArgs { url: None }
    }
}

pub struct ProxyInfoBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ProxyInfoBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_url(&mut self, url: ::flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(ProxyInfo::VT_URL, url);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> ProxyInfoBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        ProxyInfoBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<ProxyInfo<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for ProxyInfo<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("ProxyInfo");
        ds.field("url", &self.url());
        ds.finish()
    }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct ProxyInfoT {
    pub url: Option<alloc::string::String>,
}
impl Default for ProxyInfoT {
    fn default() -> Self {
        Self { url: None }
    }
}
impl ProxyInfoT {
    pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
        &self,
        _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>,
    ) -> ::flatbuffers::WIPOffset<ProxyInfo<'b>> {
        let url = self.url.as_ref().map(|x| _fbb.create_string(x));
        ProxyInfo::create(_fbb, &ProxyInfoArgs { url })
    }
}
