name: Build Artifacts

on:
  workflow_call:

permissions:
  actions: read
  contents: read

jobs:
  windows:
    uses: ./.github/workflows/Build.Windows.Job.yml

  linux:
    uses: ./.github/workflows/Build.Linux.Job.yml

  macos:
    uses: ./.github/workflows/Build.MacOS.Job.yml
