name: Publish SDK to GPR

on:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: npm-packages

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@microsoft'

      - name: Publish SDK
        run: |
          $tgz = (Get-Item sdk\*.tgz).FullName
          echo "Publishing $tgz"
          npm publish $tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
