name: Validation Infrastructure Testing

on:
  push:
    branches:
      - user/emichlin/add-seatbelt-technical-tests

concurrency:
  group: validation-infra-pr-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  dependency-feed-check:
    uses: ./.github/workflows/Dependency.Feed.Check.Job.yml

  windows:
    needs: dependency-feed-check
    uses: ./.github/workflows/Build.Windows.Job.yml

  linux:
    needs: dependency-feed-check
    uses: ./.github/workflows/Build.Linux.Job.yml

  macos:
    needs: dependency-feed-check
    uses: ./.github/workflows/Build.MacOS.Job.yml

  test:
    needs: [windows, linux, macos]
    uses: ./.github/workflows/Validation.Tests.Matrix.Job.yml
    with:
      plan: enabled